name: Continuous Integration and Continuous Deployment on Heroku

on:
    push:
    pull_request: 
    workflow_dispatch: 

jobs:    
    deploy: 
        name: Deploy to Heroku
        if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}

        steps: 
            - name: Get Code
              uses: actions/checkout@v4
              with:
                persist-credentials: false

            - name: Using Heroku Docker Deploy action
              id: deployapp
              uses: ./.github/actions/heroku-docker-deploy
              with:
                HEROKU_APP_NAME: artifixer-test
                HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}

            - name: Heroku App Link
              run: echo ${{steps.deployapp.outputs.HEROKU_APP_URL}}
            